### ISSUE TITLE
HTML Checker fails on missing favicon.ico

### ISSUE THREAD

**Issue by pierluigi** [githubtraining/ci-circle#119]
## Bug Report

**Current behavior**
The html checker status fails on the latest version due to missing favicon.ico references, which are not expected.

**Reproduction**
```
root@3caed6c498cb:~/project# bundle exec htmlproofer ./_site --check-html 
Running ["ImageCheck", "ScriptCheck", "HtmlCheck", "LinkCheck"] on ["./_site"] on *.html...


Checking 8 external links...
Ran on 5 files!


- ./_site/about/index.html
  *  internally linking to /favicon.ico, which does not exist (line 1)
     <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
- ./_site/docs/01_getting_ready_for_class/index.html
  *  internally linking to /favicon.ico, which does not exist (line 1)
     <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
- ./_site/docs/02_getting_started/index.html
  *  internally linking to /favicon.ico, which does not exist (line 1)
     <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
- ./_site/docs/2018-12-12-welcome-to-jekyll/index.html
  *  internally linking to /favicon.ico, which does not exist (line 1)
     <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
- ./_site/index.html
  *  internally linking to /favicon.ico, which does not exist (line 1)
     <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
htmlproofer 3.11.1 | Error:  HTML-Proofer found 5 failures!
```

**Expected behavior**
It should not fail on this, or the instructions should mention this case.

**Possible solution**
I have tried using the flag `--check-favicon false` however it did nothing. Oddly enough the check_favicon flag [should be disabled by default](https://github.com/gjtorikian/html-proofer#configuration), but it doesn't seem the case?

How about adding the favicon? Or finding the right way to shut down the favicon check?

Hope this helps!

**Comment by brianamarie** [comment]
This has also been brought up again via Halp by a user. I'm going to investigate this as a part of comms duty this week 👀

**Comment by brianamarie** [comment]
I have tested this by adding a favicon, and it is working. I'm going to add that to the template repository, and re-test to make sure it works.

**Comment by brianamarie** [comment]
This has been addressed. @pierluigi Thank you for raising this issue, and for your patience!
