### ISSUE TITLE
CircleCI flow out of date

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/ci-circle#122]
The sign on and authorization flow for CircleCI is no longer in sync with what we describe on the course. This is likely causing folks to drop off and should be resolved.

**Comment by hectorsector** [comment]
This seems to be blocking the course as the instructions are very far apart from the learner experience.

**Comment by brianamarie** [comment]
Thank you for opening this issue, @hectorsector. Depending on the registration numbers and the maintenance that would be involved in keeping this active, do you think this would be a course we should consider sunsetting or deactivating?

**Comment by hectorsector** [comment]
I think this might be a good idea. @brianamarie should we reach out to our friends at CircleCI to see if they're interested in transitioning to their organization? I'd be glad to help them get set up with maintaining the course themselves.

**Comment by brianamarie** [comment]
I think that's a great idea, @hectorsector. I found [this thread from 3 years ago](https://halp.githubapp.com/inboxes/services/discussions/8ed41816f2cf11e69550e2d77d09da95) when we worked with Emma, and it looks like she's the [director of marketing](https://circleci.com/about/team/) and reachable at `emma@circleci.com`. 🎉

**Comment by hectorsector** [comment]
Reached out via [Halp](https://halp.githubapp.com/inboxes/learning-lab/discussions/b7bec57cd05811ea9cdb096db1862f5f).
